// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY-VdrZ9RAX0PRtUNrPT7plLLZVyLT7yk',
    appId: '1:1079456150582:web:placeholder',
    messagingSenderId: '1079456150582',
    projectId: 'recipe-app-501c1',
    authDomain: 'recipe-app-501c1.firebaseapp.com',
    storageBucket: 'recipe-app-501c1.firebasestorage.app',
    // NOTE: This is a placeholder. To enable Firebase Messaging on web:
    // 1. Go to Firebase Console > Project Settings
    // 2. Add a Web app and copy the real appId
    // 3. Replace 'placeholder' above with the actual web app ID
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-VdrZ9RAX0PRtUNrPT7plLLZVyLT7yk',
    appId: '1:1079456150582:android:0dce078eee0fb90c509497',
    messagingSenderId: '1079456150582',
    projectId: 'recipe-app-501c1',
    storageBucket: 'recipe-app-501c1.firebasestorage.app',
  );
}
